version: "3.9"
services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: welcome123
      ORACLE_DISABLE_ASYNCH_IO: "true"
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "tnsping", "xe"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-db:1521/xe
      SPRING_DATASOURCE_USERNAME: SYSTEM
      SPRING_DATASOURCE_PASSWORD: welcome123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
