spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: welcome123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    com.manga.tracker.service.MangadexService: debug

mangadex:
  host: https://api.mangadex.org
#docker container create -it --name oracle-local -p 1521:1521 -e ORACLE_PWD=welcome123 container-registry.oracle.com/database/express:latest
